CREATE TABLE PRODUIT (
  NPRO char(5) NOT NULL,
  LIBELLE varchar(20) NOT NULL,
  PRIX decimal(5,0) NOT NULL,
  QSTOCK decimal(6,0) NOT NULL,
  PRIMARY KEY (NPRO) 
);
INSERT INTO  PRODUIT  VALUES (1,'Voiture',50,200);
INSERT INTO  PRODUIT  VALUES (2,'Moto',20,600);
INSERT INTO  PRODUIT  VALUES (3,'Téléphone',9,900);
INSERT INTO  PRODUIT  VALUES (4,'Draisienne',90,200);
INSERT INTO  PRODUIT  VALUES (5,'Cheval à bascule',2,800);

