    version: '3'
     
    services:
     
        php:
            build:
                context: ./docker/php
            ports:
                - 9000:9000
            volumes:
                - ./b2b:/srv/www/api
                - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            environment:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     
        nginx:
            image: nginx:latest
            ports:
                - 80:80
                - 443:443
            volumes:
                - ./b2b:/srv/www/api
                - ./www:/srv/www/client
                - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
                - ./docker/certbot/conf:/etc/nginx/ssl
                - ./docker/certbot/data:/var/www/certbot

            depends_on:
                - php
     
        mysql:
            image: mysql:5.7
            volumes:
                - ./docker/mysql:/docker-entrypoint-initdb.d
            ports:
                - 3306:3306
            depends_on:
                - php
            environment:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}

# certificat:
        certbot:
            image: certbot/certbot:latest
            entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
            volumes:
                - ./docker/certbot/conf:/etc/letsencrypt
                - ./docker/certbot/logs:/var/log/letsencrypt
                - ./docker/certbot/data:/var/www/certbot

            command: certonly --webroot --webroot-path=/var/www/certbot --email he201916@domain.com --agree-tos --no-eff-email -d b2b.m1-3.ephec-ti.be -d www.m1-3.ephec-ti.be

